### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by Alex-Werner** [Alex-Werner/SBTree#45]
### Expected Behavior

TypeError: Cannot read properties of undefined (reading 'find')

### Current Behavior

<img width="783" alt="image" src="https://github.com/Alex-Werner/SBTree/assets/5849920/d9dd4140-2301-4b5e-8985-eceed5c47564">

### Context

It seems caused by a mistake from the request, as closeTime is an object and not a value. 
`closeTime":{"date":"2023-09-30T00:15:59.999Z"}`

```
const replayCandles = await this.tree.findDocuments({
            closeTime: { $gte: startTime, $lte: endTime }
        });
        ```

**Comment by Alex-Werner** [comment]
In a specific case, I also stumble upon this one : 

} { fieldName: 'trades' }
/Users/alex/GitHub/WindfallerAI/WindfallerAI/node_modules/sbtree/src/types/SBTree/ops/query.js:97
              promises.push(fieldTree.find(queryFieldValue[operator], operator));
                                      ^

TypeError: Cannot read properties of undefined (reading 'find')
    at /Users/alex/GitHub/WindfallerAI/WindfallerAI/node_modules/sbtree/src/types/SBTree/ops/query.js:97:39
    at Array.forEach (<anonymous>)
    at SBTree.query (/Users/alex/GitHub/WindfallerAI/WindfallerAI/node_modules/sbtree/src/types/SBTree/ops/query.js:61:10)
    at SBTree.findDocuments (/Users/alex/GitHub/WindfallerAI/WindfallerAI/node_modules/sbtree/src/types/SBTree/methods/findDocuments.js:8:23)
    at HistoricalTradeRedispatcher.replay (file:///Users/alex/GitHub/WindfallerAI/WindfallerAI/src/managers/HistoricalTradeRedispatcher/HistoricalTradeRedispatcher.js:68:47)
    at WorldState.init (file:///Users/alex/GitHub/WindfallerAI/WindfallerAI/src/primitives/WorldState/WorldState.js:71:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WindfallerAI.start (file:///Users/alex/GitHub/WindfallerAI/WindfallerAI/src/managers/WindfallerAI/WindfallerAI.js:73:9)

Which is from an await insert, then query. 

Fix being : setTimeout....

**Comment by Alex-Werner** [comment]
Upon adding a random throw new Error() somewhere, the insert ends up failing. 

<img width="792" alt="image" src="https://github.com/Alex-Werner/SBTree/assets/5849920/8291e039-0e9f-4d6c-a2c2-e20cad03163d">
 
 Fix in SBTree might requires to re-inspect all proper promises awaiting actions. It might be the isReady(). 
 Because most of the work tested in SBTree have been via the FSAdapter, while those above are using the MemoryAdapter.
